/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sowjanya
 */
public class NewPwdJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private String username;
    private UserAccount account;

    NewPwdJPanel(JPanel userProcessContainer, EcoSystem system, UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.username = username;
        this.account = account;
        
        welcomeLabel.setText("");
        welcomeLabel.setText(account.getPerson().getFirstName()+account.getPerson().getLastName());
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        newPwdTxtField = new javax.swing.JPasswordField();
        confirmNewPwdTxtField = new javax.swing.JPasswordField();
        strengthlabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/icons8_Key_48px.png"))); // NOI18N
        jLabel2.setText("New Password");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/icons8_Key_2_48px.png"))); // NOI18N
        jLabel3.setText("Confirm Password");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        welcomeLabel.setBackground(new java.awt.Color(255, 255, 204));
        welcomeLabel.setText("<FirstName & LastName>");

        messageLabel.setBackground(new java.awt.Color(255, 255, 204));
        messageLabel.setText(".");

        newPwdTxtField.setBackground(new java.awt.Color(255, 255, 204));
        newPwdTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                newPwdTxtFieldKeyPressed(evt);
            }
        });

        confirmNewPwdTxtField.setBackground(new java.awt.Color(255, 255, 204));
        confirmNewPwdTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirmNewPwdTxtFieldFocusLost(evt);
            }
        });
        confirmNewPwdTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmNewPwdTxtFieldKeyPressed(evt);
            }
        });

        strengthlabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        strengthlabel.setText(".");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(welcomeLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(strengthlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(newPwdTxtField)
                                .addComponent(confirmNewPwdTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)))))
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(288, 288, 288))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(welcomeLabel)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(newPwdTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(confirmNewPwdTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(strengthlabel)
                .addGap(1, 1, 1)
                .addComponent(jButton1)
                .addGap(29, 29, 29)
                .addComponent(messageLabel)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Create a New Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(newPwdTxtField.getText().equals(confirmNewPwdTxtField.getText())){
            account.setPassword((confirmNewPwdTxtField.getText()));
            messageLabel.setText("");
            messageLabel.setText("Yout password has beeb reset. Pleaase logout to save the changes");
           // JOptionPane.showMessageDialog(null, "Yout password has beeb reset. Pleaase logout to save the changes");
           newPwdTxtField.setEnabled(false);
           confirmNewPwdTxtField.setEnabled(false);
           
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void newPwdTxtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newPwdTxtFieldKeyPressed
        // TODO add your handling code here:
        
        if((newPwdTxtField.getText().length()==8)){
            strengthlabel.setText("");
            strengthlabel.setText("Medium");
           }
        else if(  ((newPwdTxtField.getText().length())<8)  ){
            strengthlabel.setText("");
            strengthlabel.setText("Weak");
        }
        else if((newPwdTxtField.getText().length()>8)){
            strengthlabel.setText("");
            strengthlabel.setText("Strong"); 
        }
        
      if(newPwdTxtField.getText().length()>=15) {  
             evt.consume();
          }   
    }//GEN-LAST:event_newPwdTxtFieldKeyPressed

    private void confirmNewPwdTxtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmNewPwdTxtFieldKeyPressed
        // TODO add your handling code here:
        
       if((confirmNewPwdTxtField.getText().length()==8)){
            strengthlabel.setText("");
            strengthlabel.setText("Medium");
           }
        else if(  ((confirmNewPwdTxtField.getText().length())<8)  ){
            strengthlabel.setText("");
            strengthlabel.setText("Weak");
        }
        else if((confirmNewPwdTxtField.getText().length()>8)){
            strengthlabel.setText("");
            strengthlabel.setText("Strong"); 
        }
        
      if(confirmNewPwdTxtField.getText().length()>=15) {  
             evt.consume();
          }  
    }//GEN-LAST:event_confirmNewPwdTxtFieldKeyPressed

    private void confirmNewPwdTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmNewPwdTxtFieldFocusLost
        // TODO add your handling code here:
        strengthlabel.setText("");
    }//GEN-LAST:event_confirmNewPwdTxtFieldFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmNewPwdTxtField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JPasswordField newPwdTxtField;
    private javax.swing.JLabel strengthlabel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
