/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Company.TeamInitiative.EventCreator;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.InitiativeWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JAI
 */
public class ViewVolunteersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewVolunteersJPanel
     */
    private JPanel userProcessContainer;
    private InitiativeWorkRequest initiativeWorkRequest;

    public ViewVolunteersJPanel(JPanel userProcessContainer, WorkRequest workRequest) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.initiativeWorkRequest =(InitiativeWorkRequest)workRequest;
        populateTable();
    }

    public void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel) tblEventVolunteers.getModel();

        model.setRowCount(0);

        for (UserAccount ua : initiativeWorkRequest.getParticipatingUsers().getUserAccountList()) {
            {           
            Object[] row = new Object[4];
            
            row[0] = ua;
            row[1] = ua.getPerson().getFirstName()+" "+ua.getPerson().getLastName();
            row[2] = ua.getPerson().getMblNo();
            row[3] = ua.getPerson().getSmiles();

            model.addRow(row);
         
            }  
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEventVolunteers = new javax.swing.JTable();
        btnViewVolunteer = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Event Volunteers");

        tblEventVolunteers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Username", "Member Name", "Mobile Number", "Smiles Earned"
            }
        ));
        jScrollPane1.setViewportView(tblEventVolunteers);

        btnViewVolunteer.setText("View Volunteer's Profile");
        btnViewVolunteer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewVolunteerActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnViewVolunteer)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnBack))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewVolunteer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 341, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewVolunteerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewVolunteerActionPerformed
        int selectedRow = tblEventVolunteers.getSelectedRow();

        if (selectedRow >= 0) {
            
        UserAccount volunteerUserAccount = (UserAccount) tblEventVolunteers.getValueAt(selectedRow, 0);
 
        VolunteerProfileJPanel volunteerProfileJPanel = new VolunteerProfileJPanel(userProcessContainer, volunteerUserAccount);
        userProcessContainer.add("VolunteerProfileJPanel", volunteerProfileJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        else
            JOptionPane.showMessageDialog(null, "Select a Row from the table");
    }//GEN-LAST:event_btnViewVolunteerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewVolunteer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEventVolunteers;
    // End of variables declaration//GEN-END:variables
}
