/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CompanyMemberOrganization.CompanyMember;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.CompanyMemberOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author JAI
 */
public class CompanyMemberRoleWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CompanyMemberRoleWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private CompanyMemberOrganization companyMemberOrganization;
    private UserAccount account;
    private Enterprise enterprise;
    private EcoSystem business;
    

    public CompanyMemberRoleWorkAreaJPanel(JPanel userProcessContainer, CompanyMemberOrganization companyMemberOrganization, UserAccount account, Enterprise enterprise, EcoSystem business) {
        
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.companyMemberOrganization = companyMemberOrganization;
        this.account = account;
        this.enterprise = enterprise;
        this.business = business;
        System.out.println(""+account.getPerson());
        System.out.println(""+account.getPerson().getImageURL());
        lblRequestorName.setText(account.getPerson().getFirstName()+" "+account.getPerson().getLastName());
        lblAge.setText(String.valueOf(account.getPerson().getAge()));

        ImageIcon MyImage = new ImageIcon(System.getProperty("user.dir")+File.separator+account.getPerson().getImageURL());
        System.out.println("Image URL"+System.getProperty("user.dir")+File.separator+account.getPerson().getImageURL());
     // Taking dynamic path for the image saved
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);    
        imageLabel.setIcon(image);
        //}
        
        lblSmiles.setText(String.valueOf(account.getPerson().getSmiles()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        lblRequestorName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        requestHelpBtn = new javax.swing.JButton();
        lblSmiles = new javax.swing.JLabel();
        earnSmilesBtn = new javax.swing.JButton();
        editProfileBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        myRequestsBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));

        jLabel4.setText("Name :");

        lblRequestorName.setText("<Requestor Name>");

        jLabel5.setText("Age : ");

        lblAge.setText("<Requestor Age>");

        jLabel7.setText("Smiles :");

        requestHelpBtn.setText("Request Help");
        requestHelpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestHelpBtnActionPerformed(evt);
            }
        });

        lblSmiles.setText("<Smiles>");

        earnSmilesBtn.setText("Earn Smiles");
        earnSmilesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                earnSmilesBtnActionPerformed(evt);
            }
        });

        editProfileBtn.setText("Edit Profile");
        editProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Company Member Work Area");

        myRequestsBtn.setText("My Requests");
        myRequestsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myRequestsBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("(Profile Photo)");

        imageLabel.setMaximumSize(new java.awt.Dimension(100, 100));
        imageLabel.setMinimumSize(new java.awt.Dimension(100, 100));
        imageLabel.setName(""); // NOI18N
        imageLabel.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(earnSmilesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblRequestorName)
                                            .addComponent(lblAge)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblSmiles)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 323, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)))
                        .addGap(216, 216, 216))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(requestHelpBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editProfileBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(myRequestsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblRequestorName)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAge)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblSmiles))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                        .addComponent(editProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(requestHelpBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(myRequestsBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(earnSmilesBtn)
                        .addGap(148, 148, 148))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestHelpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestHelpBtnActionPerformed
        // TODO add your handling code here:
        CompanyMemberRequestHelpJPanel companyMemberRequestHelpJPanel = new CompanyMemberRequestHelpJPanel(userProcessContainer,companyMemberOrganization,account,enterprise,business);
        userProcessContainer.add("CompanyMemberRequestHelpJPanel", companyMemberRequestHelpJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requestHelpBtnActionPerformed

    private void earnSmilesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_earnSmilesBtnActionPerformed
        // TODO add your handling code here:
        CompanyMemberEarnASmileJPanel companyMemberEarnASmileJPanel = new CompanyMemberEarnASmileJPanel(userProcessContainer,companyMemberOrganization,account,enterprise,business);
        userProcessContainer.add("EarnASmileJPanel", companyMemberEarnASmileJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_earnSmilesBtnActionPerformed

    private void editProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileBtnActionPerformed
        // TODO add your handling code here:
        CompanyMemberEditProfileJPanel companyMemberEditProfileJPanel = new CompanyMemberEditProfileJPanel(userProcessContainer,account);
        userProcessContainer.add("CompanyMemberEditProfileJPanel", companyMemberEditProfileJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_editProfileBtnActionPerformed

    private void myRequestsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myRequestsBtnActionPerformed
        // TODO add your handling code here:
        CompanyMemberMyRequestsJPanel companyMemberMyRequestsJPanel = new CompanyMemberMyRequestsJPanel(userProcessContainer,account,companyMemberOrganization);
        userProcessContainer.add("CompanyMemberMyRequestsJPanel", companyMemberMyRequestsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_myRequestsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton earnSmilesBtn;
    private javax.swing.JButton editProfileBtn;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblRequestorName;
    private javax.swing.JLabel lblSmiles;
    private javax.swing.JButton myRequestsBtn;
    private javax.swing.JButton requestHelpBtn;
    // End of variables declaration//GEN-END:variables
}
