/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.MemberOrganization.Member;

import Business.EcoSystem;
import Business.Network.Network;
import Business.Organization.MemberOrganization;
import Business.Person.Address;
import Business.Person.Person;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.commons.io.FileUtils;


/**
 *
 * @author JAI
 */
public class EditProfileJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditProfileJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private String path;
    private ImageIcon icon;
    private String gender;
    
    

    public EditProfileJPanel(JPanel userProcessContainer,UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        
        lastNameTxtField.setEnabled(false);
        
        
        comboDesignation.setSelectedItem(0);
        comboDesignation.addItem("Student");
        comboDesignation.addItem("Software Employee");
        comboDesignation.addItem("Veteran");
        comboDesignation.addItem("Senior Citizen");
        comboDesignation.addItem("Government Services");
        
        
        
       //To display image
        ImageIcon MyImage = new ImageIcon(System.getProperty("user.dir")+File.separator+account.getPerson().getImageURL());
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);    
        imageLabel.setIcon(image);
 
        firstNameTxtField.setText(account.getPerson().getFirstName());
        lastNameTxtField.setText(account.getPerson().getLastName());
        aboutUTxtField.setText(account.getPerson().getIntro());
        comboDesignation.setSelectedIndex(account.getPerson().getIndex());
        
        if(account.getPerson().getGender().equals(maleRadioBtn.getText())){
            maleRadioBtn.setSelected(true);
        }
        else{
            feMaleRadioBtn.setSelected(true);
        }
        DateOfBirthChooser.setCalendar(account.getPerson().getCalendar());
        address1TxtField.setText(String.valueOf(account.getPerson().getAddress().getDoorNum()));
        address2TxtField.setText((account.getPerson().getAddress().getStreetName()));
        cityTxtField.setText((account.getPerson().getAddress().getCity()));
        stateTxtField.setText((account.getPerson().getAddress().getState()));
        zipTxField.setText(String.valueOf(account.getPerson().getAddress().getZipCode()));
        countryTextField.setText(account.getPerson().getAddress().getCountry());
    
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        maleRadioBtn = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        feMaleRadioBtn = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lastNameTxtField = new javax.swing.JTextField();
        comboDesignation = new javax.swing.JComboBox();
        firstNameTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DateOfBirthChooser = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        aboutUTxtField = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        countryTextField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        cityTxtField = new javax.swing.JTextField();
        stateTxtField = new javax.swing.JTextField();
        address2TxtField = new javax.swing.JTextField();
        zipTxField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        profilePicBtn = new javax.swing.JButton();
        editAccountBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        address1TxtField = new javax.swing.JTextField();
        messageLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel5.setText("        Gender");

        maleRadioBtn.setText("Male");

        jLabel2.setText("    Last Name ");

        feMaleRadioBtn.setText("Female");

        jLabel3.setText("    First Name ");

        jLabel13.setText("  Designation");

        lastNameTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lastNameTxtFieldKeyPressed(evt);
            }
        });

        firstNameTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                firstNameTxtFieldKeyPressed(evt);
            }
        });

        jLabel4.setText("Date Of Birth");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Edit your Personal Details ");

        jLabel8.setText("   About You");

        aboutUTxtField.setColumns(20);
        aboutUTxtField.setRows(5);
        jScrollPane1.setViewportView(aboutUTxtField);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Edit your Address ");

        jLabel20.setText("Street Name");

        countryTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                countryTextFieldKeyPressed(evt);
            }
        });

        jLabel21.setText("Door Number");

        cityTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cityTxtFieldKeyPressed(evt);
            }
        });

        stateTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                stateTxtFieldKeyPressed(evt);
            }
        });

        address2TxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                address2TxtFieldKeyTyped(evt);
            }
        });

        zipTxField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                zipTxFieldKeyPressed(evt);
            }
        });

        jLabel10.setText("     Country:");

        jLabel23.setText("        State ");

        jLabel24.setText("     ZipCode");

        jLabel22.setText("  City");

        saveBtn.setText("Save ");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        imageLabel.setText(".");

        profilePicBtn.setText("Upload Pic");
        profilePicBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilePicBtnActionPerformed(evt);
            }
        });

        editAccountBtn.setText("Edit Account Details");
        editAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAccountBtnActionPerformed(evt);
            }
        });

        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        address1TxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                address1TxtFieldKeyPressed(evt);
            }
        });

        messageLabel.setText(".");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel24)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(backBtn)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(address2TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(address1TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(zipTxField, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(countryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(2, 2, 2)))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(comboDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(profilePicBtn)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(maleRadioBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(feMaleRadioBtn))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(firstNameTxtField)
                                        .addComponent(lastNameTxtField)
                                        .addComponent(DateOfBirthChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(saveBtn)
                        .addGap(42, 42, 42)
                        .addComponent(editAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DateOfBirthChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maleRadioBtn)
                            .addComponent(feMaleRadioBtn)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(comboDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profilePicBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(address2TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(address1TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(zipTxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(countryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(editAccountBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(messageLabel)
                .addGap(11, 11, 11)
                .addComponent(backBtn)
                .addGap(9, 9, 9))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("   Edit Your Profile");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        
        account.getPerson().setFirstName(firstNameTxtField.getText()) ;
        account.getPerson().setIntro(aboutUTxtField.getText());
        account.getPerson().setCategory((String) comboDesignation.getSelectedItem());
        account.getPerson().setIndex(comboDesignation.getSelectedIndex());
        account.getPerson().setImageIcon((ImageIcon)imageLabel.getIcon());
        Calendar cal =DateOfBirthChooser.getCalendar();
           int datevar = cal.get(Calendar.DATE);
           int monthvar = cal.get(Calendar.MONTH)+1;
           int yearvar = cal.get(Calendar.YEAR);
           String dob_String = monthvar+"/"+datevar+"/"+yearvar ;
           String timeStamp = new SimpleDateFormat("MM/dd/yyyy").format(Calendar.getInstance().getTime());
           int age = 0;
     
            try {
           Date dob=new SimpleDateFormat("MM/dd/yyyy").parse(dob_String);
           Date currentDate=new SimpleDateFormat("MM/dd/yyyy").parse(timeStamp);
           account.getPerson().setDob(dob);
           age=currentDate.getYear()-dob.getYear();
           account.getPerson().setAge(age);
               
           } catch (ParseException ex) {
              System.out.println("Error while selecting date of birth");
             }
  
        if(maleRadioBtn.isSelected()){
            gender =maleRadioBtn.getText();
         }
        else if (feMaleRadioBtn.isSelected()){
             gender = feMaleRadioBtn.getText();
           }
        account.getPerson().setGender(gender);
        
        
        account.getPerson().getAddress().setDoorNum(Integer.parseInt(address1TxtField.getText()));
        account.getPerson().getAddress().setStreetName(address2TxtField.getText());
        account.getPerson().getAddress().setCity(cityTxtField.getText());
        account.getPerson().getAddress().setState(stateTxtField.getText());
        account.getPerson().getAddress().setCountry(countryTextField.getText());
        account.getPerson().getAddress().setZipCode(Integer.parseInt(zipTxField.getText()));
      
        
        
         messageLabel.setText("Account Details Updated");
         //JOptionPane.showMessageDialog(null, "");
     

    }//GEN-LAST:event_saveBtnActionPerformed

    private void profilePicBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilePicBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        String fileName=f.getName();
        String destinationPath= System.getProperty("user.dir")+File.separator+"src\\Images\\" +fileName;
        String savingPathForPerson="src\\Images\\" +fileName;
         try{
            Image image = ImageIO.read(f);
            Image newImg = image.getScaledInstance(100, 100, Image.SCALE_SMOOTH);// Add this changes to get a scaled image
            ImageIcon icon = new ImageIcon(newImg);
            account.getPerson().setImageIcon(icon);
            imageLabel.setIcon(account.getPerson().getImageIcon());           // Displaying the image once it is attached
   
            File destination = new File(destinationPath);
            if(!destination.exists())
            destination.createNewFile();
            FileUtils.copyFile(f,destination);
            System.out.println("NO Error");
            account.getPerson().setImageURL(savingPathForPerson);/// Saving data in persons' image path attribute(String)
            }          
            catch(IOException ioe){
            System.out.println("Exception occured while setting Image on the Label!");
            }

    }//GEN-LAST:event_profilePicBtnActionPerformed

    private void editAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAccountBtnActionPerformed
        // TODO add your handling code here:
         EditAccountDetailsJPanel registerPanel = new EditAccountDetailsJPanel(userProcessContainer,account);
         userProcessContainer.add("EditAccountDetails", registerPanel);
         CardLayout layout = (CardLayout) userProcessContainer.getLayout();
         layout.next(userProcessContainer);
    }//GEN-LAST:event_editAccountBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void firstNameTxtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNameTxtFieldKeyPressed
        // TODO add your handling code here:
        if(firstNameTxtField.getText().length()>=15) {  
       JOptionPane.showMessageDialog(null, "Only 15 characters are allowed");   
       evt.consume();
      } 
        
    }//GEN-LAST:event_firstNameTxtFieldKeyPressed

    private void lastNameTxtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastNameTxtFieldKeyPressed
        // TODO add your handling code here:
        
       if(lastNameTxtField.getText().length()>=15) {  
       JOptionPane.showMessageDialog(null, "Only 15 characters are allowed");   
       evt.consume();
      }
    }//GEN-LAST:event_lastNameTxtFieldKeyPressed

    private void address2TxtFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_address2TxtFieldKeyTyped
        // TODO add your handling code here:
       if(address2TxtField.getText().length()>=15) {  
       JOptionPane.showMessageDialog(null, "No more than 15 characters are allowed");   
       evt.consume();
     }
    }//GEN-LAST:event_address2TxtFieldKeyTyped

    private void address1TxtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_address1TxtFieldKeyPressed
        // TODO add your handling code here:
            int key = evt.getKeyCode();
       if ((key >= KeyEvent.VK_0 && key <= KeyEvent.VK_9) || (key == KeyEvent.VK_NUM_LOCK) || (key == KeyEvent.VK_BACK_SPACE) || (key == KeyEvent.VK_SHIFT)) {
           address1TxtField.setEditable(true);
       } else {
           address1TxtField.setEditable(false);
           JOptionPane.showMessageDialog(null, "Only digits are allowed");
           address1TxtField.setText("");
       }   
       
       if(address1TxtField.getText().length()>=7) {  
       JOptionPane.showMessageDialog(null, "No more than 7 characters are allowed");   
       evt.consume();
       }
        
    }//GEN-LAST:event_address1TxtFieldKeyPressed

    private void zipTxFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zipTxFieldKeyPressed
        // TODO add your handling code here:
      int key = evt.getKeyCode();
       if ((key >= KeyEvent.VK_0 && key <= KeyEvent.VK_9) || (key == KeyEvent.VK_NUM_LOCK) || (key == KeyEvent.VK_BACK_SPACE) || (key == KeyEvent.VK_SHIFT)) {
           zipTxField.setEditable(true);
       } else {
           zipTxField.setEditable(false);
           JOptionPane.showMessageDialog(null, "Only digits are allowed");
           zipTxField.setText("");
       }  
       
        if(zipTxField.getText().length()>=7) {  
       JOptionPane.showMessageDialog(null, "No more than 7 characters are allowed");   
       evt.consume();
       }
    }//GEN-LAST:event_zipTxFieldKeyPressed

    private void countryTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_countryTextFieldKeyPressed
        // TODO add your handling code here:
       if(countryTextField.getText().length()>=20) {  
       JOptionPane.showMessageDialog(null, "No more than 15 characters are allowed");   
       evt.consume();
       }
    }//GEN-LAST:event_countryTextFieldKeyPressed

    private void stateTxtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stateTxtFieldKeyPressed
        // TODO add your handling code here:
       if(stateTxtField.getText().length()>=20) {  
       JOptionPane.showMessageDialog(null, "No more than 15 characters are allowed");   
       evt.consume();
       }
    }//GEN-LAST:event_stateTxtFieldKeyPressed

    private void cityTxtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityTxtFieldKeyPressed
        // TODO add your handling code here:
      if(stateTxtField.getText().length()>=15) {  
       JOptionPane.showMessageDialog(null, "No more than 15 characters are allowed");   
       evt.consume();
       }
    }//GEN-LAST:event_cityTxtFieldKeyPressed

     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateOfBirthChooser;
    private javax.swing.JTextArea aboutUTxtField;
    private javax.swing.JTextField address1TxtField;
    private javax.swing.JTextField address2TxtField;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField cityTxtField;
    private javax.swing.JComboBox comboDesignation;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JButton editAccountBtn;
    private javax.swing.JRadioButton feMaleRadioBtn;
    private javax.swing.JTextField firstNameTxtField;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameTxtField;
    private javax.swing.JRadioButton maleRadioBtn;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JButton profilePicBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField stateTxtField;
    private javax.swing.JTextField zipTxField;
    // End of variables declaration//GEN-END:variables
}
