/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Philanthropist;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.WelfareFundDispenserOrganization;
import Business.Organization.WelfareOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;

import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;


/**
 *
 * @author Sudeep
 */
public class PhilanthropistAdminManagerAnalytics extends javax.swing.JPanel {

    /**
     * Creates new form PhilanthropistAdminManagerAnalytics
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private ArrayList<Organization> organizationList;
    private ArrayList<UserAccount> userAccountList;

    public PhilanthropistAdminManagerAnalytics(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.enterprise = enterprise;
        this.userProcessContainer = userProcessContainer;
        organizationList = new ArrayList<>();
        userAccountList = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        supplierAnalytics = new javax.swing.JButton();
        dispenserAnalytics = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        supplierAnalytics.setText("Supplier Analytics");
        supplierAnalytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierAnalyticsActionPerformed(evt);
            }
        });

        dispenserAnalytics.setText("Provider Analytics");
        dispenserAnalytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispenserAnalyticsActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Philanthropist Analytics Work Area");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Click button to view the funds Supplier are willing to donate for social cause");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Click button to view the funds requested by Dispenser for social cause");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dispenserAnalytics, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplierAnalytics, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addComponent(supplierAnalytics)
                .addGap(68, 68, 68)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addComponent(dispenserAnalytics)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void supplierAnalyticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierAnalyticsActionPerformed
        // TODO add your handling code here:
        DefaultPieDataset pieDataset=new DefaultPieDataset();
        
        
        
        
        //DefaultCategoryDataset barchartdata = new DefaultCategoryDataset();
        organizationList = enterprise.getOrganizationDirectory().getOrganizationList();
        for (Organization org : organizationList) {
            if (org instanceof WelfareOrganization) {
                userAccountList = org.getUserAccountDirectory().getUserAccountList();

                for (UserAccount ua : userAccountList) {
                    //Float revenue = ua.getTotalAmt();

                    //barchartdata.setValue(ua.getTotalAmt(), "Funds", (ua.getPerson().getFirstName() + ' ' + ua.getPerson().getLastName()));
                    pieDataset.setValue((ua.getPerson().getFirstName() + ' ' + ua.getPerson().getLastName()), ua.getTotalAmt());
                }

    }//GEN-LAST:event_supplierAnalyticsActionPerformed
  }
        
        JFreeChart chart=ChartFactory.createPieChart3D("Contribution of Funds By Supplier", pieDataset,true,true,true);
        PiePlot3D p=(PiePlot3D)chart.getPlot();
        //p.setForegroundAlpha(TOP_ALIGNMENT);
        ChartFrame frame=new ChartFrame("PieChart for Supplier Funds",chart);
        frame.setVisible(true);
        frame.setSize(650,550);
        /*JFreeChart barchart = ChartFactory.createBarChart("Contribution of Funds By Supplier", "Supplier", "Funds", barchartdata, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot barchrt = barchart.getCategoryPlot();
        barchrt.setRangeGridlinePaint(Color.ORANGE);
        ChartFrame frame = new ChartFrame("Barchart for Supplier Funds", barchart);
        frame.setVisible(true);
        frame.setSize(650, 550);*/
    }
    
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void dispenserAnalyticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispenserAnalyticsActionPerformed
        // TODO add your handling code here:
        //DefaultCategoryDataset barchartdata = new DefaultCategoryDataset();
        DefaultPieDataset pieDataset=new DefaultPieDataset();
        organizationList = enterprise.getOrganizationDirectory().getOrganizationList();
        for (Organization org : organizationList) {
            if (org instanceof WelfareFundDispenserOrganization) {
                userAccountList = org.getUserAccountDirectory().getUserAccountList();

                for (UserAccount ua : userAccountList) {
                    //Float revenue = ua.getTotalAmt();

                    //barchartdata.setValue(ua.getTotalAmt(), "Funds", (ua.getPerson().getFirstName() + ' ' + ua.getPerson().getLastName()));
                    pieDataset.setValue((ua.getPerson().getFirstName() + ' ' + ua.getPerson().getLastName()), ua.getTotalAmt());
                }

    }                                                 
  }
        JFreeChart chart=ChartFactory.createPieChart3D("Funds Requested By Each Provider", pieDataset,true,true,true);
        PiePlot3D p=(PiePlot3D)chart.getPlot();
        //p.setForegroundAlpha(TOP_ALIGNMENT);
        ChartFrame frame=new ChartFrame("PieChart of Provider Funds request",chart);
        frame.setVisible(true);
        frame.setSize(650,550);
        /*JFreeChart barchart = ChartFactory.createBarChart("Funds Requested By Each Provider", "Dispenser", "Funds", barchartdata, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot barchrt = barchart.getCategoryPlot();
        barchrt.setRangeGridlinePaint(Color.GREEN);
        ChartFrame frame = new ChartFrame("Barchart of Provider Funds request", barchart);
        frame.setVisible(true);
        frame.setSize(650, 550);*/
    }//GEN-LAST:event_dispenserAnalyticsActionPerformed
      
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton dispenserAnalytics;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton supplierAnalytics;
    // End of variables declaration//GEN-END:variables
}
